# 🚀 AI Trading Dashboard - Secrets Configuration
# Add these to your Streamlit Cloud Secrets section

# 📲 Telegram Bot Configuration
[telegram]
bot_token = "YOUR_BOT_TOKEN_HERE"  # Get from @BotFather
chat_id = "@SHADOWCLAW007"
user_id = "YOUR_TELEGRAM_USER_ID"  # Get from @userinfobot

# 📊 Google Sheets Configuration
[google_sheets]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"

# 📊 Portfolio Google Sheet
portfolio_sheet_id = "YOUR_GOOGLE_SHEET_ID"
portfolio_sheet_name = "Portfolio"

# 📰 News API Configuration
[news]
newsapi_key = "YOUR_NEWSAPI_KEY"  # Get from newsapi.org
alpha_vantage_key = "YOUR_ALPHA_VANTAGE_KEY"  # Get from alphavantage.co

# 🔔 Alert Settings
[alerts]
alert_time = "09:25"
timezone = "US/Eastern"
enable_voice = true
enable_sms = false

# 📞 Twilio (Optional for SMS/Voice)
[twilio]
account_sid = "YOUR_TWILIO_SID"
auth_token = "YOUR_TWILIO_TOKEN"
from_phone = "+1234567890"
to_phone = "+1234567890"

# 🎯 Trading Settings
[trading]
paper_trading = true
default_position_size = 0.1  # 10%
default_stop_loss = 0.05     # 5%
default_take_profit = 0.15   # 15%
risk_per_trade = 0.02        # 2%
